module.exports = {
  "serverName": "lxserver",
  "proxy.enabled": false,
  "proxy.header": "x-real-ip",
  "bindIP": "0.0.0.0",
  "port": 9527,
  "user.enablePath": true,
  "user.enableRoot": false,
  "user.enablePublicRestriction": true,
  "user.enablePublicNonAdminLocalMusic": false,
  "user.enablePublicNonAdminBrowserDownload": true,
  "user.enablePublicNonAdminServerCache": false,
  "user.enablePublicFavorites": false,
  "user.enablePublicNonAdminAccess": false,
  "user.enableCustomMusicDir": false,
  "user.enableLoginCacheRestriction": false,
  "user.enableCacheSizeLimit": false,
  "user.cacheSizeLimit": 2000,
  "maxSnapshotNum": 10,
  "list.addMusicLocationType": "top",
  "disableTelemetry": false,
  "users": [
    {
      "name": "admin",
      "password": "password",
      "dataPath": "D:\\project\\lxserver\\data\\users\\admin_21232f"
    },
    {
      "name": "m",
      "password": "music123654",
      "dataPath": "D:\\project\\lxserver\\data\\users\\m_6f8f57"
    }
  ],
  "frontend.password": "123456",
  "webdav.enable": false,
  "webdav.url": "",
  "webdav.username": "",
  "webdav.password": "",
  "webdav.syncPath": "/lx-sync",
  "webdav.backupPath": "/lx-sync-backups",
  "sync.interval": 60,
  "sync.backupInterval": 24,
  "player.enableAuth": false,
  "player.password": "123456",
  "proxy.all.enabled": false,
  "proxy.all.address": "",
  "admin.path": "/admin",
  "player.path": "/",
  "subsonic.enable": true,
  "subsonic.path": "/rest",
  "subsonic.enableDebug": false,
  "subsonic.onlineSearch": true,
  "subsonic.onlineSearchMode": "fallback",
  "subsonic.onlineSearchSources": "wy,tx,kw,kg,mg",
  "subsonic.lyricTranslation": true,
  "subsonic.cacheOnPlay": false,
  "subsonic.playCacheFirst": true,
  "subsonic.quality.enabled": true,
  "subsonic.quality.priority": "flac,320k,128k",
  "subsonic.quality.clientCapMode": "soft",
  "subsonic.source.priority": "kw,tx,wy,mg,kg",
  "subsonic.source.crossPlatform": true,
  "subsonic.source.autoSwitchCustom": true,
  "singer.sourcePriority": [
    "tx",
    "wy"
  ],
  "artist.maxFetchPages": 20,
  "cache.namingPattern": "simple",
  "system.allowUnsafeVM": false
}